<a href="https://colab.research.google.com/github/yunariver/newproject/blob/main/%EB%B0%91%EB%B0%94%EB%8B%A5%EB%B6%80%ED%84%B0_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_GPT_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 데이터셋 다운로드하기
!wget https://raw.githubusercontent.com/shop2world/data/master/input.txt

# 데이터셋을 읽어서 확인하기
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print("데이터셋의 글자 수: ", len(text))

# 처음 1000자를 확인해보기
print(text[:1000])

#설명:
#위 코드는 작은 규모의 셰익스피어 텍스트 데이터셋을 다운로드하고, 해당 데이터셋을 읽어서 내용을 확인하는 코드입니다.
#먼저 `wget` 명령어를 사용하여 데이터셋을 다운로드합니다. 그런 다음 `open` 함수를 사용하여 파일을 열고, `read` 메서드를 통해 파일 내용을 읽어옵니다.
#읽어온 데이터의 길이를 확인하고, 처음 1000자를 출력하여 데이터의 내용을 확인합니다.

--2023-10-18 02:35:21--  https://raw.githubusercontent.com/shop2world/data/master/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  --.-KB/s    in 0.04s   

2023-10-18 02:35:21 (29.4 MB/s) - ‘input.txt.1’ saved [1115394/1115394]

데이터셋의 글자 수:  1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it

In [ ]:
# 주어진 텍스트에서 발생하는 모든 고유한 문자 확인
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)



 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [ ]:
# 문자열을 정수 리스트로 변환하고(토큰), 그 반대로 정수 리스트를 문자열로 변환하는 과정
import string

# 확장된 문자 리스트 생성
chars = sorted(list(set(text + string.ascii_letters + string.digits + string.punctuation)))
print(len(chars))  # chars 리스트의 크기 출력

# 인코딩 및 디코딩 함수 정의
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s if c in stoi]  # 인코딩 시 stoi에 없는 문자는 무시
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hello shop2world"))
print(decode(encode("hello shop2world")))




96
[73, 70, 77, 77, 80, 1, 84, 73, 80, 81, 19, 88, 80, 83, 77, 69]
hello shop2world


In [ ]:
# 데이터셋을 인코딩하여 torch.Tensor로 저장하는 과정 (비정형데이터->정형데이터)
# 데이터 전처리 과정은 텍스트 데이터를 딥러닝 모델에 입력으로 사용하기 위해 필요한 단계
import torch #  PyTorch는 딥러닝 프레임워크: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)#인코딩된 정수 리스트를 torch.Tensor로 변환
print(data.shape, data.dtype)#data.shape는 텐서의 형태(크기), data.dtype는 텐서의 데이터 타입
print(data[:1000]) #  텍스트의 처음 1000개 문자가 GPT 모델에게 어떻게 보일지를 나타냅니다

torch.Size([1115394]) torch.int64
tensor([39, 74, 83, 84, 85,  1, 36, 74, 85, 74, 91, 70, 79, 27,  0, 35, 70, 71,
        80, 83, 70,  1, 88, 70,  1, 81, 83, 80, 68, 70, 70, 69,  1, 66, 79, 90,
         1, 71, 86, 83, 85, 73, 70, 83, 13,  1, 73, 70, 66, 83,  1, 78, 70,  1,
        84, 81, 70, 66, 76, 15,  0,  0, 34, 77, 77, 27,  0, 52, 81, 70, 66, 76,
        13,  1, 84, 81, 70, 66, 76, 15,  0,  0, 39, 74, 83, 84, 85,  1, 36, 74,
        85, 74, 91, 70, 79, 27,  0, 58, 80, 86,  1, 66, 83, 70,  1, 66, 77, 77,
         1, 83, 70, 84, 80, 77, 87, 70, 69,  1, 83, 66, 85, 73, 70, 83,  1, 85,
        80,  1, 69, 74, 70,  1, 85, 73, 66, 79,  1, 85, 80,  1, 71, 66, 78, 74,
        84, 73, 32,  0,  0, 34, 77, 77, 27,  0, 51, 70, 84, 80, 77, 87, 70, 69,
        15,  1, 83, 70, 84, 80, 77, 87, 70, 69, 15,  0,  0, 39, 74, 83, 84, 85,
         1, 36, 74, 85, 74, 91, 70, 79, 27,  0, 39, 74, 83, 84, 85, 13,  1, 90,
        80, 86,  1, 76, 79, 80, 88,  1, 36, 66, 74, 86, 84,  1, 46, 66, 83, 68,
      

In [ ]:
# 데이터를 훈련 세트(train set)와 검증 세트(validation set)로 분할
n = int(0.9*len(data)) # 데이터의 길이의 90%에 해당하는 값을 n 변수에 저장
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 5
train_data[:block_size+1]

tensor([39, 74, 83, 84, 85,  1])

In [ ]:
#트레인 , test 분리
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"입력값이 {context} 일경우 대상은: {target}")

입력값이 tensor([39]) 일경우 대상은: 74
입력값이 tensor([39, 74]) 일경우 대상은: 83
입력값이 tensor([39, 74, 83]) 일경우 대상은: 84
입력값이 tensor([39, 74, 83, 84]) 일경우 대상은: 85
입력값이 tensor([39, 74, 83, 84, 85]) 일경우 대상은: 1


In [ ]:
torch.manual_seed(777)
batch_size = 4 # 병렬로 처리할 독립적인 시퀀스의 개수
block_size = 8 # 예측에 사용할 수 있는 최대 문맥 길이

def get_batch(split):
    # 입력(x)과 대상(y)의 작은 배치 데이터를 생성합니다.
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))#예)[1,4,3,0]
    #선택 가능한 범위에서 batch_size 개수만큼의 임의의 정수를 선택하여 반환
    #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y
# 'train' 데이터로 get_batch 함수를 호출하여 입력(xb)과 대상(yb)의 작은 배치 데이터를 생성합니다.
xb, yb = get_batch('train')
# 생성된 입력(xb)의 shape와 내용을 출력합니다.
print('입력값:')
print(xb.shape)
print(xb)
# 생성된 대상(yb)의 shape와 내용을 출력합니다.
print('대상(targets):')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # 배치 차원
    for t in range(block_size): # 시간 차원
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"입력값이 {context.tolist()} 일경우 대상값: {target}")

입력값:
torch.Size([4, 8])
tensor([[ 1, 73, 66, 87, 70,  1, 67, 77],
        [70, 70, 69, 84, 13,  1, 74, 79],
        [52, 70, 68, 80, 79, 69,  1, 44],
        [79, 27,  0, 70, 87, 70, 83, 90]])
대상(targets):
torch.Size([4, 8])
tensor([[73, 66, 87, 70,  1, 67, 77, 70],
        [70, 69, 84, 13,  1, 74, 79,  1],
        [70, 68, 80, 79, 69,  1, 44, 70],
        [27,  0, 70, 87, 70, 83, 90,  1]])
----
입력값이 [1] 일경우 대상값: 73
입력값이 [1, 73] 일경우 대상값: 66
입력값이 [1, 73, 66] 일경우 대상값: 87
입력값이 [1, 73, 66, 87] 일경우 대상값: 70
입력값이 [1, 73, 66, 87, 70] 일경우 대상값: 1
입력값이 [1, 73, 66, 87, 70, 1] 일경우 대상값: 67
입력값이 [1, 73, 66, 87, 70, 1, 67] 일경우 대상값: 77
입력값이 [1, 73, 66, 87, 70, 1, 67, 77] 일경우 대상값: 70
입력값이 [70] 일경우 대상값: 70
입력값이 [70, 70] 일경우 대상값: 69
입력값이 [70, 70, 69] 일경우 대상값: 84
입력값이 [70, 70, 69, 84] 일경우 대상값: 13
입력값이 [70, 70, 69, 84, 13] 일경우 대상값: 1
입력값이 [70, 70, 69, 84, 13, 1] 일경우 대상값: 74
입력값이 [70, 70, 69, 84, 13, 1, 74] 일경우 대상값: 79
입력값이 [70, 70, 69, 84, 13, 1, 74, 79] 일경우 대상값: 1
입력값이 [52] 일경우 대상값: 70
입력값이 [52, 70] 일경우 대상

In [ ]:
print(xb) # xb는 Transformer 모델에 입력으로 사용되는 데이터

tensor([[ 1, 73, 66, 87, 70,  1, 67, 77],
        [70, 70, 69, 84, 13,  1, 74, 79],
        [52, 70, 68, 80, 79, 69,  1, 44],
        [79, 27,  0, 70, 87, 70, 83, 90]])


In [ ]:
import torch
import torch.nn as nn #파이토치 Neural Networks
from torch.nn import functional as F # 신경망 모델 함수들을 제공
torch.manual_seed(777)

class LanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # 각 토큰은 다음 토큰에 대한 로짓을 직접 읽어옵니다 (룩업 테이블에서)
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
      # idx와 targets는 모두 (B, T) 형태의 정수 텐서입니다
        logits = self.token_embedding_table(idx) # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx는 현재 문맥의 인덱스로 이루어진 (B, T) 배열입니다
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            # 예측 결과를 얻습니다
            logits = logits[:, -1, :]# (B, C) 형태로 변환됨
            # 확률을 얻기 위해 softmax를 적용합니다
            probs = F.softmax(logits, dim=-1)# (B, C)
            # 확률을 얻기 위해 softmax를 적용합니다
            idx_next = torch.multinomial(probs, num_samples=1)# (B, C)
            # 샘플링된 인덱스를 현재 시퀀스에 추가합니다
            idx = torch.cat((idx, idx_next), dim=1)# (B, T+1)

        return idx

vocab_size = len(chars) #chars 리스트의 길이를 vocab_size로 사용
m = LanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 96])
tensor(5.1830, grad_fn=<NllLossBackward0>)

;L3?qhavOPYQl<ZI8@\M1??^gkte{S(&Q>?cF#GI_o67mEzGKNL9\yj<L XF kp~V2@NG-goSUevy/K}q>&!vL8jEf!xWv`=k\o;


In [ ]:
# PyTorch 옵티마이저
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(10000): # 많이 돌리면 ...

    # 데이터의 미니배치를 추출합니다.
    xb, yb = get_batch('train')

    # 손실을 평가합니다.
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.4121220111846924


In [ ]:
print(decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


Aur;
SINond he ir sishu, witeife; Whes! a, natherbenthance r hangh
Pre f cknthecher f in-esareetocag GAUThanspurthathee ter meafls. beer o:
KE:
CHa Justh;
Thooswillacot(&GIOLUES:


Asields ffouler ie thennd su,
Assth ld taim t d pe w

LENoieay Hashasoney?"hiz, a t t t h ds s b n if tinghey arg po ad f breeey RARauns\IUMo s he hifeanouly plld,
Sousen hre
Th,
Mithir s omouswinc! lifomelito, heeds ke r,
Thele
LENGea r he M`4ja an fet I lthe, pill be m; iny gomoo ves,

PRIOWhar; ba o st thioura Coa 


In [ ]:
import torch
import torch.nn as nn #파이토치 Neural Networks
from torch.nn import functional as F # 신경망 모델 함수들을 제공
torch.manual_seed(777)

# hyperparameters
batch_size = 32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
# ------------

torch.manual_seed(1337)

# 데이터셋 다운로드하기
!wget https://raw.githubusercontent.com/shop2world/data/master/input.txt

# 데이터셋을 읽어서 확인하기
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# 문자열을 정수 리스트로 변환하고, 그 반대로 정수 리스트를 문자열로 변환하는 과정
import string

# 확장된 문자 리스트 생성
chars = sorted(list(set(text + string.ascii_letters + string.digits + string.punctuation)))
print(len(chars))  # chars 리스트의 크기 출력

# 인코딩 및 디코딩 함수 정의
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s if c in stoi]  # 인코딩 시 stoi에 없는 문자는 무시
decode = lambda l: ''.join([itos[i] for i in l])

#트레인 , test 분리
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    # 입력(x)과 대상(y)의 작은 배치 데이터를 생성합니다.
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))#예)[1,4,3,0]
    #선택 가능한 범위에서 batch_size 개수만큼의 임의의 정수를 선택하여 반환
    #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

#새로 추가한 부분
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class LanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # 각 토큰은 다음 토큰에 대한 로짓을 직접 읽어옵니다 (룩업 테이블에서)
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
      # idx와 targets는 모두 (B, T) 형태의 정수 텐서입니다
        logits = self.token_embedding_table(idx) # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx는 현재 문맥의 인덱스로 이루어진 (B, T) 배열입니다
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            # 예측 결과를 얻습니다
            logits = logits[:, -1, :]# (B, C) 형태로 변환됨
            # 확률을 얻기 위해 softmax를 적용합니다
            probs = F.softmax(logits, dim=-1)# (B, C)
            # 확률을 얻기 위해 softmax를 적용합니다
            idx_next = torch.multinomial(probs, num_samples=1)# (B, C)
            # 샘플링된 인덱스를 현재 시퀀스에 추가합니다
            idx = torch.cat((idx, idx_next), dim=1)# (B, T+1)

        return idx

#추가한 부분
model = LanguageModel(vocab_size)
m = model.to(device)
# PyTorch 옵티마이저
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)


print(decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

vocab_size = len(chars) #chars 리스트의 길이를 vocab_size로 사용
m = LanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))


--2023-10-18 02:35:40--  https://raw.githubusercontent.com/shop2world/data/master/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.2’

input.txt.2         100%[===================>]   1.06M  --.-KB/s    in 0.04s   

2023-10-18 02:35:40 (24.1 MB/s) - ‘input.txt.2’ saved [1115394/1115394]

96

gN4xS`:R2JWUr_9GFsm,,[j*pJ0NV}lhv
ou)_B>lb6<8ThB[] "5!*=%Z:SInY6'.'<9r7l|h_K&`aCCL>V1b56~_eZz/S0:GcF
torch.Size([256, 96])
tensor(5.2187, grad_fn=<NllLossBackward0>)
step 0: train loss 5.0909, val loss 5.0970
step 300: train loss 4.7353, val loss 4.7371
step 600: train loss 4.3972, val loss 4.4062
step 900: train loss 4.1033, val loss 4.1241
step 1200: train loss 3.8532, val loss 3.8667
step 1500: train loss 3.62

In [ ]:
'''
이 코드는 PyTorch를 사용하여 언어 모델을 생성하는 과정을 보여주는 예시입니다. 이 코드는 다음과 같은 내용을 포함하고 있습니다.
'''
'''
1. 라이브러리 임포트: torch, torch.nn, torch.nn.functional 라이브러리를 임포트합니다.
PyTorch의 Neural Networks 모듈과 신경망 함수들을 사용하기 위해 이 라이브러리들을 임포트합니다.
'''
import torch
import torch.nn as nn #파이토치 Neural Networks
from torch.nn import functional as F # 신경망 모델 함수들을 제공
torch.manual_seed(777)

'''2하이퍼파라미터 설정:
학습에 필요한 하이퍼파라미터들을 설정합니다.
batch_size, block_size, max_iters, eval_interval, learning_rate, device, eval_iters 등이 설정되어 있습니다.'''

batch_size = 32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
# ------------

torch.manual_seed(1337)

'''
3데이터셋 다운로드 및 전처리: wget 명령어를 사용하여 데이터셋을 다운로드하고, 해당 데이터셋을 읽어서 텍스트를 정수 리스트로 변환하는 작업이 수행됩니다. 이때, 문자를 정수로 인코딩하고 정수를 다시 문자로 디코딩하는 작업을 위한 사전(stoi, itos)을 생성합니다.

'''

# 데이터셋 다운로드하기
!wget https://raw.githubusercontent.com/shop2world/data/master/input.txt

# 데이터셋을 읽어서 확인하기
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# 문자열을 정수 리스트로 변환하고, 그 반대로 정수 리스트를 문자열로 변환하는 과정
import string

# 확장된 문자 리스트 생성
chars = sorted(list(set(text + string.ascii_letters + string.digits + string.punctuation)))
print(len(chars))  # chars 리스트의 크기 출력

# 인코딩 및 디코딩 함수 정의
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s if c in stoi]  # 인코딩 시 stoi에 없는 문자는 무시
decode = lambda l: ''.join([itos[i] for i in l])

#트레인 , test 분리
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

'''
4get_batch 함수: 학습 데이터를 배치 단위로 가져오는 함수입니다.
train_data와 val_data에서 랜덤하게 배치 데이터를 추출하여 입력(x)과 대상(y)으로 분할합니다.
'''

def get_batch(split):
    # 입력(x)과 대상(y)의 작은 배치 데이터를 생성합니다.
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))#예)[1,4,3,0]
    #선택 가능한 범위에서 batch_size 개수만큼의 임의의 정수를 선택하여 반환
    #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

'''
*새로 추가한 부분
5.estimate_loss 함수: 모델의 평가 손실을 추정하는 함수입니다.
주어진 반복 횟수(eval_iters)만큼 학습 데이터와 검증 데이터에 대해 손실을 계산하여 평균을 구합니다.
!학습과 검증 데이터의 손실을 추정하는 함수 estimate_loss를 정의하였습니다.
함수 내부에서는 입력으로 받은 모델을 평가 모드로 변경하고(model.eval()), 주어진 횟수(eval_iters)만큼
반복하여 손실을 계산합니다. 계산된 손실들의 평균을 구하여 학습과 검증 데이터의 손실을 추정합니다.
이후 모델을 다시 학습 모드로 변경합니다(model.train()).
이렇게 함수로 정의하면 코드를 더 간결하고 모듈화된 형태로 관리할 수 있습니다.
함수를 호출하여 학습과 검증 데이터의 손실을 추정하고 출력합니다.
'''
# 학습과 검증 데이터의 손실을 추정하는 함수 정의
def estimate_loss(model, get_batch, eval_iters):
    model.eval()
    losses_dict = {}
    with torch.no_grad():
        for split in ['train', 'val']:
            losses = torch.zeros(eval_iters)
            for k in range(eval_iters):
                X, Y = get_batch(split)
                logits, loss = model(X, Y)
                losses[k] = loss.item()
            losses_dict[split] = losses.mean()
    model.train()
    return losses_dict

# 함수 호출하여 손실 추정
losses_dict = estimate_loss(model, get_batch, eval_iters)
print(f"step {iter}: train loss {losses_dict['train']:.4f}, val loss {losses_dict['val']:.4f}")


'''
6.LanguageModel 클래스: 언어 모델을 정의하는 클래스입니다.
입력으로 주어진 인덱스에 대해 다음 토큰에 대한 로짓을 읽어오기 위해 룩업 테이블을 사용하는 Embedding 레이어를 포함합니다.
forward 메서드에서는 모델의 순전파를 수행하고, generate 메서드에서는 주어진 인덱스를 기반으로 모델을 사용하여 새로운 텍스트를 생성합니다.
*변경 내용:아래 코드는 언어 모델을 정의하는 LanguageModel 클래스를 함수 내부에 정의하여 반환하는 방식으로 변경하였습니다.
함수 define_language_model은 언어 모델을 정의하는 클래스를 내부에서 생성하고, 해당 클래스의 인스턴스를 반환합니다.
이렇게 함수로 정의하면 코드를 더 간결하고 모듈화된 형태로 관리할 수 있습니다. 함수를 호출하여 m 변수로 언어 모델을 사용할 수 있습니다.

'''
# 언어 모델을 정의하는 함수
def define_language_model(vocab_size):
    class LanguageModel(nn.Module):
        def __init__(self, vocab_size):
            super().__init__()
            # 각 토큰은 다음 토큰에 대한 로짓을 직접 읽어옵니다 (룩업 테이블에서)
            self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

        def forward(self, idx, targets=None):
            # idx와 targets는 모두 (B, T) 형태의 정수 텐서입니다
            logits = self.token_embedding_table(idx)  # (B, T, C)

            if targets is None:
                loss = None
            else:
                B, T, C = logits.shape
                logits = logits.view(B * T, C)
                targets = targets.view(B * T)
                loss = F.cross_entropy(logits, targets)

            return logits, loss

        def generate(self, idx, max_new_tokens):
            # idx는 현재 문맥의 인덱스로 이루어진 (B, T) 배열입니다
            for _ in range(max_new_tokens):
                logits, loss = self(idx)
                # 예측 결과를 얻습니다
                logits = logits[:, -1, :]  # (B, C) 형태로 변환됨
                # 확률을 얻기 위해 softmax를 적용합니다
                probs = F.softmax(logits, dim=-1)  # (B, C)
                # 확률을 얻기 위해 softmax를 적용합니다
                idx_next = torch.multinomial(probs, num_samples=1)  # (B, C)
                # 샘플링된 인덱스를 현재 시퀀스에 추가합니다
                idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1)

            return idx

    # 언어 모델 클래스 인스턴스 생성 및 반환
    return LanguageModel(vocab_size)

# 언어 모델 정의
m = define_language_model(vocab_size)
m = m.to(device)


'''
#추가한 부분!
7모델 초기화와 옵티마이저 설정: LanguageModel 클래스로부터 모델을 초기화하고, AdamW 옵티마이저를 설정합니다.
'''
# 모델 초기화와 옵티마이저 설정을 함수로 정의
def initialize_model_and_optimizer():
    model = LanguageModel(vocab_size)
    model.to(device)  # 모델을 GPU로 이동
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
    return model, optimizer

# 함수 호출하여 모델과 옵티마이저 초기화
m, optimizer = initialize_model_and_optimizer()



print(decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

vocab_size = len(chars) #chars 리스트의 길이를 vocab_size로 사용
m = LanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

'''
추가한 부분!
8학습과 생성: 주어진 반복 횟수(max_iters)만큼 학습을 수행하고, 일정 간격(eval_interval)마다 평가 손실을 출력합니다.
또한 generate 메서드를 사용하여 학습한 모델을 기반으로 새로운 텍스트를 생성합니다.
'''
# 학습과 생성을 수행하는 함수 정의
def train_and_generate(model, optimizer, max_iters, eval_interval, estimate_loss, get_batch):
    for iter in range(max_iters):
        # 일정 간격으로 train과 val 데이터에 대한 손실을 평가합니다
        if iter % eval_interval == 0:
            losses = estimate_loss(model, get_batch, eval_iters)  # 인자 추가- estimate_loss 함수를 호출할 때, 필요한 인자인 model, get_batch, eval_iters를 모두 전달
            print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

        # 데이터의 배치를 무작위로 추출합니다
        xb, yb = get_batch('train')

        # 손실을 평가합니다
        logits, loss = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

    # 모델로부터 생성합니다
    context = torch.zeros((1, 1), dtype=torch.long, device=device)
    print(decode(model.generate(context, max_new_tokens=500)[0].tolist()))

# 함수 호출
train_and_generate(m, optimizer, max_iters, eval_interval, estimate_loss, get_batch)  # model 대신 m으로 수정




--2023-10-18 02:35:51--  https://raw.githubusercontent.com/shop2world/data/master/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.3’

input.txt.3         100%[===================>]   1.06M  --.-KB/s    in 0.04s   

2023-10-18 02:35:51 (26.7 MB/s) - ‘input.txt.3’ saved [1115394/1115394]

96
step 2999: train loss 2.9188, val loss 2.9307

Y"Ue#Fv~H7dr*H,-#GEwtU{=|>-^}bS\AHPZ5.X:1W}D~#%Qlb!c}Sox UWp^Ay0g,,LV47s`,j j782f-Wj.ws.eREnN;dgx?fM
torch.Size([256, 96])
tensor(5.1578, grad_fn=<NllLossBackward0>)
step 0: train loss 5.1201, val loss 5.1366
step 300: train loss 5.1122, val loss 5.1352
step 600: train loss 5.1140, val loss 5.1349
step 900: train loss 5.1154, val loss 5.1344
step 1200: train loss 5.11

In [ ]:
#윈도우 vs code용
import torch
import torch.nn as nn
from torch.nn import functional as F
import subprocess
import string

torch.manual_seed(777)

batch_size = 32
block_size = 8
max_iters = 10000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

# 데이터셋 다운로드하기
#wget_command = "wget https://raw.githubusercontent.com/shop2world/data/master/input.txt"
#subprocess.run(wget_command, shell=True)

import subprocess

# 데이터셋 다운로드하기 (curl 사용)
curl_command = "curl -O https://raw.githubusercontent.com/shop2world/data/master/input.txt"
subprocess.run(curl_command, shell=True)

# 데이터셋을 읽어서 확인하기
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# 문자열을 정수 리스트로 변환하고, 그 반대로 정수 리스트를 문자열로 변환하는 과정
chars = sorted(list(set(text + string.ascii_letters + string.digits + string.punctuation)))
print(len(chars))
# 인코딩 및 디코딩 함수 정의
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s if c in stoi]
decode = lambda l: ''.join([itos[i] for i in l])
#트레인 , test 분리
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]
'''
get_batch 함수: 학습 데이터를 배치 단위로 가져오는 함수입니다.
train_data와 val_data에서 랜덤하게 배치 데이터를 추출하여 입력(x)과 대상(y)으로 분할합니다.
'''
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y
# 언어 모델을 정의하는 함수
class LanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx

vocab_size = len(chars)
m = LanguageModel(vocab_size)
m = m.to(device)
# 모델 초기화와 옵티마이저 설정을 함수로 정의
def initialize_model_and_optimizer():
    model = LanguageModel(vocab_size)
    model = model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
    return model, optimizer

model, optimizer = initialize_model_and_optimizer()
# 학습과 검증 데이터의 손실을 추정하는 함수 정의
def estimate_loss(model, get_batch, eval_iters):
    model.eval()
    losses_dict = {}
    with torch.no_grad():
        for split in ['train', 'val']:
            losses = torch.zeros(eval_iters)
            for k in range(eval_iters):
                X, Y = get_batch(split)
                logits, loss = model(X, Y)
                losses[k] = loss.item()
            losses_dict[split] = losses.mean()
    model.train()
    return losses_dict

# 함수 호출하여 손실 추정
losses_dict = estimate_loss(model, get_batch, eval_iters)
print(f"step {max_iters}: train loss {losses_dict['train']:.4f}, val loss {losses_dict['val']:.4f}")
# 학습과 생성을 수행하는 함수 정의
def train_and_generate(model, optimizer, max_iters, eval_interval, estimate_loss, get_batch):
    for iter in range(max_iters):
        # 일정 간격으로 train과 val 데이터에 대한 손실을 평가합니다
        if iter % eval_interval == 0:
            losses = estimate_loss(model, get_batch, eval_iters)
            print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

        # 데이터의 배치를 무작위로 추출합니다
        xb, yb = get_batch('train')

        # 손실을 평가합니다
        logits, loss = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

    # 모델로부터 생성합니다
    context = torch.zeros((1, 1), dtype=torch.long, device=device)
    print(decode(model.generate(context, max_new_tokens=500)[0].tolist()))

# 함수 호출
train_and_generate(model, optimizer, max_iters, eval_interval, estimate_loss, get_batch)


96
step 10000: train loss 5.1251, val loss 5.1153
step 0: train loss 5.1257, val loss 5.1245
step 300: train loss 4.7485, val loss 4.7542
step 600: train loss 4.4163, val loss 4.4205
step 900: train loss 4.1209, val loss 4.1182
step 1200: train loss 3.8495, val loss 3.8647
step 1500: train loss 3.6280, val loss 3.6306
step 1800: train loss 3.4295, val loss 3.4413
step 2100: train loss 3.2589, val loss 3.2706
step 2400: train loss 3.1162, val loss 3.1336
step 2700: train loss 3.0049, val loss 3.0092
step 3000: train loss 2.9155, val loss 2.9286
step 3300: train loss 2.8329, val loss 2.8344
step 3600: train loss 2.7669, val loss 2.7787
step 3900: train loss 2.7114, val loss 2.7263
step 4200: train loss 2.6764, val loss 2.6787
step 4500: train loss 2.6434, val loss 2.6572
step 4800: train loss 2.6019, val loss 2.6232
step 5100: train loss 2.5896, val loss 2.5966
step 5400: train loss 2.5668, val loss 2.5862
step 5700: train loss 2.5572, val loss 2.5722
step 6000: train loss 2.5352, val lo

In [ ]:
'''
Self-attention의 핵심 개념은 "Query, Key, Value" 메커니즘입니다.
입력 시퀀스의 각 요소에 대해 Query(Q), Key(K), Value(V) 벡터를 생성하여 유사도를 계산하고,
이를 활용하여 각 요소에 대한 다른 가중치를 부여합니다.
이를 통해 모델은 자기 자신에게 질문을 던지고, 이를 통해 입력 시퀀스 내에서 중요한 정보와 관련성을 파악합니다.
'''
import torch

# 임베딩 테이블 생성
embedding_table = torch.tensor([[0.1, 0.2, 0.3],   # 임베딩: "l"
                                [0.4, 0.5, 0.6],   # 임베딩: "am"
                                [0.7, 0.8, 0.9]])  # 임베딩: "sexy"

'''
Query(Q), Key(K), Value(V)를 생성합니다.

"I"의 Query(Q): [0.1, 0.2, 0.3]

"I"의 Key(K): [0.1, 0.2, 0.3]

"I"의 Value(V): [0.1, 0.2, 0.3]

"am"의 Query(Q): [0.4, 0.5, 0.6]

"am"의 Key(K): [0.4, 0.5, 0.6]

"am"의 Value(V): [0.4, 0.5, 0.6]

"sexy"의 Query(Q): [0.7, 0.8, 0.9]

"sexy"의 Key(K): [0.7, 0.8, 0.9]

"sexy"의 Value(V): [0.7, 0.8, 0.9]

유사도(Attention Score)를 계산합니다.

"I"와 "am"의 유사도: Query(Q) * Key(K) = [0.04, 0.1, 0.18]
"I"와 "sexy"의 유사도: Query(Q) * Key(K) = [0.49, 0.64, 0.81]
"am"와 "sexy"의 유사도: Query(Q) * Key(K) = [0.28, 0.4, 0.54]

두 벡터 A와 B의 내적 = A[0] * B[0] + A[1] * B[1] + ... + A[n] * B[n]

소프트맥스(softmax)를 적용하여 가중치를 얻습니다.

"I"와 "am"의 가중치: softmax([0.04, 0.1, 0.18]) = [0.168, 0.336, 0.496]
"I"와 "sexy"의 가중치: softmax([0.49, 0.64, 0.81]) = [0.104, 0.285, 0.611]
"am"와 "sexy"의 가중치: softmax([0.28, 0.4, 0.54]) = [0.186, 0.316, 0.498]
각 쌍의 가중치를 사용하여 각 요소에 대한 다른 가중치를 부여합니다.

"I"의 새로운 벡터: Value(V) * "I"의 가중치 = [0.1 * 0.168, 0.2 * 0.336, 0.3 * 0.496] = [0.0168, 0.0672, 0.1488]
"am"의 새로운 벡터: Value(V) * "am"의 가중치 = [0.4 * 0.104, 0.5 * 0.285, 0.6 * 0.611] = [0.0416, 0.1425, 0.3666]
"sexy"의 새로운 벡터: Value(V) * "sexy"의 가중치 = [0.7 * 0.186, 0.8 * 0.316, 0.9 * 0.498] = [0.1302, 0.2528, 0.4482]

'''

# 입력 문장
sentence = torch.tensor([0, 1, 2])  # 인덱스로 문장 표현: "l am sexy"

# Query(Q), Key(K), Value(V) 벡터 생성
Q = embedding_table[sentence]
K = embedding_table[sentence]
V = embedding_table[sentence]

print("입력 문장:")
print(sentence)
print("Query(Q) 벡터:")
print(Q)
print("Key(K) 벡터:")
print(K)
print("Value(V) 벡터:")
print(V)



입력 문장:
tensor([0, 1, 2])
Query(Q) 벡터:
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])
Key(K) 벡터:
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])
Value(V) 벡터:
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])


**보충수업 -유사도**
"I"와 "am"의 어텐션 내적(유사도) 값은 총 3개입니다.

어텐션(Attention) 메커니즘에서는 주어진 입력(쿼리와 키)에 대해 모든 가능한 쌍의 내적(유사도) 값을 계산합니다.
이 예시에서는 "I"와 "am" 두 단어로 이루어진 입력이 주어졌으므로, 두 단어 간의 쿼리와 키를 모두 조합하여 유사도를 계산합니다.

계산 가능한 내적(유사도) 값은 다음과 같습니다:
- "I"의 쿼리(Q) * "I"의 키(K) = 0.1 * 0.1 = 0.01
- "I"의 쿼리(Q) * "am"의 키(K) = 0.1 * 0.4 = 0.04
- "am"의 쿼리(Q) * "I"의 키(K) = 0.4 * 0.1 = 0.04

위의 3개의 값이 "I"와 "am"의 어텐션 내적(유사도) 값으로 계산 가능합니다. 이러한 값들은 소프트맥스 함수를 거쳐 가중치를 얻고, 이를 사용하여 각 단어의 새로운 벡터를 계산하는 데 사용됩니다.

**내적 계산**

예를 들어, 두 벡터 A와 B가 다음과 같다고 가정합니다:

A = [1, 2, 3]
B = [2, 4, 6]

두 벡터 A와 B의 유사도 내적 값은 각 위치의 요소들을 곱한 뒤 그 합을 구하는 것입니다. 따라서 유사도 내적 값은 다음과 같이 계산됩니다:

유사도 내적 값 = 1 * 2 + 2 * 4 + 3 * 6 = 2 + 8 + 18 = 28

위 예시에서 두 벡터 A와 B의 유사도 내적 값은 28입니다. 이것은 두 벡터 간의 유사도를 측정하는 데 사용되며, 어텐션 메커니즘과 같은 다양한 기계 학습 모델에서 중요한 부분을 차지하는 계산 방법 중 하나입니다. 각 위치의 요소들을 곱한 후 합산함으로써 두 벡터의 유사도를 측정하는 간단한 방법이기 때문에 쉽게 이해할 수 있습니다.

그럼 다음의 예시가 있을때를 봅니다.

A = [1, 2, 3]
B = [2, 4, 6]
C= [7,8,9]

예시에서 주어진 벡터 A, B, C에 대해 유사도 내적 값을 구하겠습니다.

1. A와 B의 유사도 내적 값:

A = [1, 2, 3]
B = [2, 4, 6]

유사도 내적 값 = 1 * 2 + 2 * 4 + 3 * 6 = 2 + 8 + 18 = 28

2. A와 C의 유사도 내적 값:

A = [1, 2, 3]
C = [7, 8, 9]

유사도 내적 값 = 1 * 7 + 2 * 8 + 3 * 9 = 7 + 16 + 27 = 50

3. B와 C의 유사도 내적 값:

B = [2, 4, 6]
C = [7, 8, 9]

유사도 내적 값 = 2 * 7 + 4 * 8 + 6 * 9 = 14 + 32 + 54 = 100

따라서, 벡터 A와 B의 유사도 내적 값은 28, A와 C의 유사도 내적 값은 50, 그리고 B와 C의 유사도 내적 값은 100입니다. 각 벡터 쌍에 대해 유사도 내적 값을 계산할 수 있습니다. 이는 유사도 측정을 활용하여 두 벡터의 유사도를 수치화하는데 사용됩니다.

**"positional encoding"("positional embedding")**

- 위치 정보를 벡터로 표현하는 방법

위치에 대한 정보가 없는 경우 self-attention에서는 단어들의 순서와 위치를 고려하지 않고, 모든 단어들이 동일한 방식으로 처리됩니다. 이로 인해


아래와 같은 문제들이 발생할 수 있습니다:

1. 순서 정보 손실: 문장의 단어들이 위치 정보 없이 동일한 방식으로 처리되기 때문에 단어들의 순서 정보가 손실됩니다. 예를 들어 "I am sexy"와 "Sexy am I"라는 문장은 단어들의 순서가 다르지만, 위치 정보가 없는 self-attention에서는 두 문장을 동일하게 처리할 수 있습니다.

2. 문장의 의미 파악 어려움: 단어들의 순서와 위치 정보가 무시되므로 문장의 의미를 파악하는 데에 어려움이 발생할 수 있습니다. 문장에서 단어들의 순서는 문장의 의미를 이해하는 데에 중요한 역할을 합니다.

3. 모호한 결과: 위치 정보가 없는 self-attention은 동일한 단어가 다른 위치에 나타나더라도 동일하게 처리하므로, 모호한 결과가 발생할 수 있습니다. 예를 들어 "I love playing soccer"와 "I love playing piano"라는 문장에서 "love"라는 단어는 동일하지만, 위치 정보가 없는 self-attention에서는 두 문장을 동일하게 처리할 수 있어 모호성이 발생합니다.

따라서 self-attention에서는 위치 정보를 인코딩해주는 positional encoding과 같은 방법을 사용하여 단어들의 순서와 위치 정보를 모델에 제공해야 합니다. 위치 정보를 포함한 self-attention을 사용하면 문장의 의미를 파악하고 단어들의 순서를 이해하는 데에 더 효과적이고 정확한 결과를 얻을 수 있습니다.

- 위치를 배열로 임베딩

위치를 배열로 임베딩할 때 삼각함수(sin, cos)를 사용하는 방법은 Transformer 모델의 positional encoding 방식 중 하나입니다. 이 방식은 위치 임베딩을 구하는 데에 있어서 주기적인 패턴을 부여하여 각 위치에 고유한 임베딩 값을 부여하는 데에 유용합니다.

일반적으로 자연어 처리에서 문장이나 문서의 단어들은 배열 형태로 구성됩니다. 예를 들어, "I am going to the park"라는 문장을 배열로 표현하면 [I, am, going, to, the, park]와 같이 됩니다. 이 배열에서 각 단어의 위치(인덱스)는 중요한 정보를 가집니다. 하지만 단어들의 위치에 따라 간단히 증가하는 자연수만으로는 문장의 복잡한 구조와 순서를 충분히 표현하기 어렵습니다.

따라서 Transformer 모델에서는 삼각함수를 활용하여 주기적인 패턴을 생성하고, 이를 위치 임베딩으로 활용합니다. 삼각함수를 사용하면 주기적인 변화를 가지는 값들을 생성할 수 있으며, 이를 통해 단어들의 위치에 따라 다양한 임베딩 값을 부여할 수 있습니다. 이렇게 생성된 위치 임베딩은 모델이 단어들의 상대적인 위치를 학습하는 데에 도움을 주고, 어텐션 메커니즘에서 단어들의 순서를 파악하는 데에 유용합니다.

따라서 Transformer에서 삼각함수를 사용하여 위치 임베딩을 계산하는 방법은 문장의 구조와 순서를 더 잘 표현할 수 있는 효과적인 방법 중 하나입니다.

지금까지 배운 내용을 추가하겠습니다.
기존 코드는 Transformer 블록을 사용하여 구성되며, 입력 시퀀스의 각 요소에 대해 Query(Q), Key(K), Value(V) 벡터를 생성하여 유사도를 계산하고, 이를 활용하여 각 요소에 대한 다른 가중치를 부여합니다. 이러한 Self-Attention 메커니즘을 통해 모델은 입력 시퀀스 내에서 중요한 정보와 관련성을 파악합니다. 또한 이 코드에서는 위치 임베딩(Positional Embedding)을 적용하는 방법 중 하나인 삼각함수(sin, cos)를 사용하여 위치를 배열로 임베딩합니다. 삼각함수를 활용하는 방식은 입력 시퀀스 내에서 단어의 위치를 벡터로 인코딩하는 데에 주기적인 패턴을 부여하여 각 위치에 고유한 임베딩 값을 부여하는데에 사용됩니다. 이러한 위치 임베딩을 사용하여 모델은 단어들의 상대적인 위치를 이해하고 문맥을 파악하는 데에 도움을 줄 수 있습니다. 이렇게 주어진 코드에 Transformer 블록을 추가하고, 삼각함수를 사용하여 위치 임베딩을 적용하는 방법을 설명해 드리겠습니다.

1. Transformer 블록 추가:
   - Transformer 블록은 `Block` 클래스로 정의됩니다. 이 블록은 다수의 self-attention 레이어와 feed-forward 레이어로 구성되며, 모든 레이어는 레지듀얼 커넥션과 레이어 정규화가 적용됩니다.
   - `MultiHeadAttention` 클래스는 self-attention의 여러 헤드를 병렬로 수행하는 클래스입니다. 이 클래스의 인스턴스를 `Block` 클래스의 `sa` 속성으로 사용합니다.
   - `FeedFoward` 클래스는 단순한 선형 레이어와 활성화 함수인 ReLU로 구성된 클래스입니다. 이 클래스의 인스턴스를 `Block` 클래스의 `ffwd` 속성으로 사용합니다.

2. 위치 임베딩 적용:
   - 위치 임베딩은 트랜스포머 모델에서 단어의 상대적인 위치를 반영하는데 사용됩니다. 삼각함수(sin, cos)를 사용하여 주기적인 패턴을 부여하여 각 위치에 고유한 임베딩 값을 부여하는 방법을 사용합니다.
   - 위치 임베딩은 `LanguageModel` 클래스의 `forward` 메서드 내에서 적용됩니다.
   - `self.position_embedding_table`은 입력 시퀀스의 각 위치에 대해 삼각함수 값을 가진 테이블로 초기화됩니다.
   - `pos_emb = self.position_embedding_table(torch.arange(T, device=device))`: 입력 시퀀스의 길이에 해당하는 벡터를 생성하여 위치 임베딩 값을 가져옵니다.
   - `x = tok_emb + pos_emb`: 단어 임베딩과 위치 임베딩을 더하여 최종 입력으로 사용합니다.

3. 학습과 생성 수행:
   - `train_and_generate` 함수는 모델을 주어진 학습 횟수(`max_iters`)와 평가 간격(`eval_interval`)에 맞게 학습하고, 주어진 학습 데이터에 대해 손실을 출력합니다.
   - 학습이 끝난 후, 모델로부터 생성된 텍스트를 확인합니다. 이를 위해 `model.generate` 함수를 호출하여 주어진 초기 문맥(`context`)에서 새로운 토큰들을 생성합니다.

이렇게 코드에 Transformer 블록과 위치 임베딩을 추가하여 Self-Attention 메커니즘을 통해 모델이 입력 시퀀스 내에서 중요한 정보와 관련성을 파악하도록 구성되었습니다.

아래는 추가된 코드입니다.

In [ ]:
'''
이 코드에는 이제 MultiHeadAttention 레이어와 TransformerBlock의 구현이 포함되어 있으며, 이를 LanguageModel에 적용하고 있습니다.
이것으로 모델은 올바르게 작동해야 하며, 이제 Self-Attention 메커니즘이 포함된 Transformer 블록에 의해 제공된 위치 임베딩과 함께 작동합니다.
전체 코드를 실행해보시면, 기대한 대로 언어 모델링 작업을 수행할 수 있을 것입니다.
'''
import torch
import torch.nn as nn
from torch.nn import functional as F
import subprocess
import string

torch.manual_seed(777)

batch_size = 32
block_size = 8
max_iters = 10000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

# 데이터셋 다운로드하기 (curl 사용)
curl_command = "curl -O https://raw.githubusercontent.com/shop2world/data/master/input.txt"
subprocess.run(curl_command, shell=True)

# 데이터셋을 읽어서 확인하기
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# 문자열을 정수 리스트로 변환하고, 그 반대로 정수 리스트를 문자열로 변환하는 과정
chars = sorted(list(set(text + string.ascii_letters + string.digits + string.punctuation)))
print(len(chars))
# 인코딩 및 디코딩 함수 정의
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s if c in stoi]
decode = lambda l: ''.join([itos[i] for i in l])
#트레인 , test 분리
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]
'''
get_batch 함수: 학습 데이터를 배치 단위로 가져오는 함수입니다.
train_data와 val_data에서 랜덤하게 배치 데이터를 추출하여 입력(x)과 대상(y)으로 분할합니다.
'''
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y
# 언어 모델을 정의하는 함수
class LanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx

vocab_size = len(chars)
m = LanguageModel(vocab_size)
m = m.to(device)
# 모델 초기화와 옵티마이저 설정을 함수로 정의
def initialize_model_and_optimizer():
    model = LanguageModel(vocab_size)
    model = model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
    return model, optimizer

model, optimizer = initialize_model_and_optimizer()
# 학습과 검증 데이터의 손실을 추정하는 함수 정의
def estimate_loss(model, get_batch, eval_iters):
    model.eval()
    losses_dict = {}
    with torch.no_grad():
        for split in ['train', 'val']:
            losses = torch.zeros(eval_iters)
            for k in range(eval_iters):
                X, Y = get_batch(split)
                logits, loss = model(X, Y)
                losses[k] = loss.item()
            losses_dict[split] = losses.mean()
    model.train()
    return losses_dict

# 함수 호출하여 손실 추정
losses_dict = estimate_loss(model, get_batch, eval_iters)
print(f"step {max_iters}: train loss {losses_dict['train']:.4f}, val loss {losses_dict['val']:.4f}")

# Transformer 블록 구현
class MultiHeadAttention(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        self.heads = nn.ModuleList([nn.Linear(n_embd, n_embd) for _ in range(n_head)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(0.1)

    def forward(self, x):
        B, T, C = x.shape
        n_head = len(self.heads)
        attn_weights = torch.stack([head(x) for head in self.heads], dim=2)  # (B, T, n_head, C)
        attn_weights = F.softmax(attn_weights, dim=3)
        out = attn_weights @ x  # (B, T, n_head, C) @ (B, T, C) -> (B, T, n_head, C)
        out = out.sum(dim=2)  # (B, T, C)
        out = self.dropout(out)
        out = self.proj(out)
        return out

class PositionalEmbedding(nn.Module):
    def __init__(self, n_embd, max_len=512):
        super().__init__()
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, n_embd, 2).float() * -(math.log(10000.0) / n_embd))
        pe = torch.zeros(max_len, n_embd)
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)].detach()

class TransformerBlock(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        self.attn = MultiHeadAttention(n_embd, n_head)
        self.norm1 = nn.LayerNorm(n_embd)
        self.mlp = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.GELU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(0.1)
        )
        self.norm2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x

# 언어 모델 정의에 TransformerBlock 적용
class LanguageModel(nn.Module):
    def __init__(self, vocab_size, n_embd=512, n_head=32):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding = PositionalEmbedding(n_embd)
        self.transformer_block = TransformerBlock(n_embd, n_head)
        self.ln_f = nn.LayerNorm(n_embd)
        self.head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding(torch.arange(idx.size(1), device=device))  # (T, C)
        x = tok_emb + pos_emb  # (B, T, C)
        x = self.transformer_block(x)
        logits = self.head(self.ln_f(x))

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss


# 함수 호출
train_and_generate(model, optimizer, max_iters, eval_interval, estimate_loss, get_batch)


96
step 10000: train loss 5.1251, val loss 5.1153
step 0: train loss 5.1257, val loss 5.1245
step 300: train loss 4.7485, val loss 4.7542
step 600: train loss 4.4163, val loss 4.4205
step 900: train loss 4.1209, val loss 4.1182
step 1200: train loss 3.8495, val loss 3.8647
step 1500: train loss 3.6280, val loss 3.6306
step 1800: train loss 3.4295, val loss 3.4413
step 2100: train loss 3.2589, val loss 3.2706
step 2400: train loss 3.1162, val loss 3.1336
step 2700: train loss 3.0049, val loss 3.0092
step 3000: train loss 2.9155, val loss 2.9286
step 3300: train loss 2.8329, val loss 2.8344
step 3600: train loss 2.7669, val loss 2.7787
step 3900: train loss 2.7114, val loss 2.7263
step 4200: train loss 2.6764, val loss 2.6787
step 4500: train loss 2.6434, val loss 2.6572
step 4800: train loss 2.6019, val loss 2.6232
step 5100: train loss 2.5896, val loss 2.5966
step 5400: train loss 2.5668, val loss 2.5862
step 5700: train loss 2.5572, val loss 2.5722
step 6000: train loss 2.5352, val lo

In [ ]:
#11 강 - 셀프 어텐션(Self-attention) 시뮬레이션
import torch
import torch.nn as nn
import torch.nn.functional as F

# 난수 생성을 위한 시드 설정
torch.manual_seed(1337)

# 입력 데이터 크기 설정
batch_size = 4     # 배치 크기
sequence_length = 8  # 시퀀스 길이
embedding_dim = 32  # 임베딩 차원

# 무작위로 초기화된 입력 데이터 생성
input_data = torch.randn(batch_size, sequence_length, embedding_dim)

# 단일 어텐션 헤드를 사용하는 self-attention을 살펴봅니다.

# 각 어텐션 헤드의 크기 설정
head_size = 16

# 키(key), 쿼리(query), 값(value)를 위한 선형 레이어 정의
key_layer = nn.Linear(embedding_dim, head_size, bias=False)
query_layer = nn.Linear(embedding_dim, head_size, bias=False)
value_layer = nn.Linear(embedding_dim, head_size, bias=False)

# 입력 데이터를 각 레이어로 전달하여 키(key), 쿼리(query), 값(value) 계산
keys = key_layer(input_data)     # (batch_size, sequence_length, head_size)
queries = query_layer(input_data) # (batch_size, sequence_length, head_size)

# 어텐션 가중치 행렬 계산
attention_weights = torch.matmul(queries, keys.transpose(-2, -1)) # (batch_size, sequence_length, sequence_length)

# 마스크를 사용하여 어텐션 가중치를 정규화하고 불필요한 부분을 무시
mask = torch.tril(torch.ones(sequence_length, sequence_length))  # 하삼각 행렬 생성
# 하삼각 행렬 생성 도표 -  주 대각선 아래에 있는 요소가 모두 1로 채워진 행렬
# 1 0 0 0
# 1 1 0 0
# 1 1 1 0
# 1 1 1 1

attention_weights = attention_weights.masked_fill(mask == 0, float('-inf'))  # 불필요한 부분을 음의 무한대로 대체
attention_weights = F.softmax(attention_weights, dim=-1)  # 소프트맥스 함수를 사용하여 정규화

# 값(value)에 어텐션 가중치를 적용하여 최종 출력 생성
values = value_layer(input_data)  # (batch_size, sequence_length, head_size)
outputs = torch.matmul(attention_weights, values)  # (batch_size, sequence_length, head_size)

# 최종 출력의 모양 확인
output_shape = outputs.shape

# 결과 출력
print("최종 출력의 모양:", output_shape)



최종 출력의 모양: torch.Size([4, 8, 16])
